### ISSUE TITLE
Pop up assisted help for MT4

### ISSUE THREAD

**Issue by JoeyUson** [L-I-V/MQL-Tools#17]
Just downloaded this extension and really a great help for studying MT4. All works fine and the popup helps a lot however there are some function not coming up when cursor is place over.

**Here are list for creating/modifying indicators:**
SetIndexStyle, 
SetIndexLabel, 
ObjectSet, 
IndicatorShortName (showing INDICATOR_SHORTNAME only), 
SetIndexArrow,
SetIndexDrawBegin,
IndicatorDigits,
IndicatorCounted,

**Here for EA**
MarketInfo,
AccountBalance,
OrderMagicNumber,
OrderSymbol,
OrderType,
IsTradeAllowed,
IsTradeContextBusy,
OrderOpenPrice,
OrderSymbol,
OrderOpenTime,
OrderStopLoss,
OrderModify,
OrderTicket,
OrderTakeProfit,
iMAOnArray

If you could  show how to add these in Pop Up I can help..

Regards,
Joey

**Comment by L-I-V** [comment]
Hints are not displayed because you are using MQL4, the extension description states that autocompletion and tooltips for the functions of MQL5!
![chrome_wi0Ddy2f3M](https://user-images.githubusercontent.com/114299712/212483534-568468eb-77ff-4ed4-a787-d0622ccf8e28.png)
In the next update, I plan to add descriptions of the MQL4 functions.

**Comment by JoeyUson** [comment]
My broker only support MT4 even I like to update to MT5. Thanks for immediate response. I really appreciate your efforts
